// GENERATED by targets/esp32/tools/gen_assets.py - do not edit.
#pragma once
#include <stdint.h>

// ---- tuning (generated from app/js/swarm.js + settings.js + tuning-meta.js)
enum TKey : uint8_t {
  T_marineSpawnRateMult,
  T_maxLings,
  T_maxBanes,
  T_maxMarines,
  T_lingW,
  T_baneW,
  T_marineW,
  T_eggW,
  T_lingBump,
  T_baneBump,
  T_marineBump,
  T_respawnInterval,
  T_respawnBatch,
  T_marineWaveLo,
  T_marineWaveHi,
  T_marineRespawnLo,
  T_marineRespawnHi,
  T_marineSpawnGap,
  T_marineSpawnInset,
  T_marineWaveSizeLo,
  T_marineWaveSizeHi,
  T_marineRespawnSizeLo,
  T_marineRespawnSizeHi,
  T_retargetInterval,
  T_aimInterval,
  T_morphAge,
  T_morphCooldown,
  T_morphChancePerSec,
  T_eggTimeMin,
  T_eggTimeMax,
  T_eggHatchMult,
  T_splatLife,
  T_splatBase,
  T_splatFadeStart,
  T_baneSplashR,
  T_baneSplashDamage,
  T_baneHp,
  T_corpseLife,
  T_marineSplatScale,
  T_baneSplatScale,
  T_lingHp,
  T_marineHp,
  T_marineShootDamage,
  T_marineShootInterval,
  T_lingBiteDamage,
  T_lingBiteInterval,
  T_marineHealPct,
  T_marineHealInterval,
  T_marineGroupWeight,
  T_marineAwayWeight,
  T_marineTurnRate,
  T_marineFleeHpPct,
  T_marineKiteFrac,
  T_marineRangeMult,
  T_allyRadius,
  T_attackGroupSize,
  T_marineScanRadius,
  T_marineGroupRadius,
  T_attackOdds,
  T_berserkSpeedMult,
  T_lingFleeSpeedMult,
  T_berserkBanes,
  T_berserkCatchRadius,
  T_berserkUntilDeath,
  T_zergSpeed,
  T_terranSpeed,
  T_marineTactics,
  T_marineEntrySpeed,
  T_marineEntryDepth,
  T_marineSightMult,
  T_hour24,
  T_showSeconds,
  T_showClock,
  T_landscape,
  T_showHealthBars,
  T_unitCount,
  T_unitSpeed,
  T_gameSpeed,
  T_unitScale,
  T_brightness,
  T_fpsCap,
  T_COUNT
};
struct TMeta {
  const char* key;
  float def;
  uint8_t isBool;
  uint8_t advanced;
  uint8_t group;      // index into TGROUPS
  const char* meaning;
};
extern const TMeta TMETA[T_COUNT];
extern const char* const TGROUPS[];
extern const uint8_t TGROUP_COUNT;

// ---- sprites (straight RGB565 + separate A8 alpha)
struct SpriteFrame { uint16_t w, h; const uint16_t* rgb; const uint8_t* a; };
struct SpriteSet { uint8_t n; uint16_t srcW, srcH; const SpriteFrame* frames; };
/* Copy sprite pixels from flash to heap (flash reads miss the 32 KB cache). */
void spritesToRam();
extern const SpriteSet SPR_LING;
extern const SpriteSet SPR_BANE;
extern const SpriteSet SPR_EGG;
extern const SpriteSet SPR_MWALK;
extern const SpriteSet SPR_MATK;

// ---- fonts (A8 coverage masks; colour applied at draw time)
struct Glyph { uint32_t off; uint8_t w, h; int8_t xo, yo; uint8_t adv; };
struct Font { uint8_t first, last; int8_t ascent, descent; const Glyph* glyphs; const uint8_t* alpha; };
extern const Font FONT_TIME;
extern const Font FONT_SEC;
extern const Font FONT_DATE;
extern const Font FONT_TEXT;

// ---- background 240x320 (4-bit indices into a 16-colour RGB565 palette)
extern const uint16_t BG_PAL_P[16];
extern const uint8_t BG_NIB_P[38400];
// ---- background 320x240 (4-bit indices into a 16-colour RGB565 palette)
extern const uint16_t BG_PAL_L[16];
extern const uint8_t BG_NIB_L[38400];
