/* Clockling - trained commander brains (generated by tools/sim/train.js;
 * do not edit by hand). Empty until the next training run: the Overmind /
 * Commander pickers only appear once a race has a Trained brain. */
var BRAINS = { zerg: {}, terran: {} };
