/* Clockling - trained commander brains (generated by tools/sim/train.js;
 * do not edit by hand). Each brain is a set of decision settings layered
 * over the tuning when picked in Settings (zergBrain / terranBrain). */
var BRAINS = {
    zerg: { Trained: {"attackOdds":1.49,"attackGroupSize":22,"zergSmarts":true,"zergPatience":87.75,"zergAllInOdds":7.34,"zergStandoff":2.32,"zergCornerDist":0.04,"ovJoinRadius":6,"ovSurround":58.56,"ovBaneHold":true,"ovBaneClump":3,"ovBaneMaxHold":17.38,"ovFrontMorph":0.44,"berserkBanes":6,"morphChancePerSec":1} },
    terran: { Trained: {"marineMicro":false,"marineSquads":false,"marineCtrlGroups":4,"marineCtrlGroupSize":12,"marineFlank":true,"marineFlankAngle":36.79,"marineStimPush":false,"marineEliteKite":false,"marineSpawnMode":1,"stimGroupMax":7,"stimRegroupDist":0.49,"marineKiteFrac":0.68,"marineFleeHpPct":0.38,"marineSightMult":3.23,"marineGroupWeight":0.86,"marineAwayWeight":0.82} }
};
