/* Clockling - TUNING & SETTINGS metadata.
 * For every key: visibility class (Visible/Advanced), default and a plain-English
 * meaning. Optional: options (dropdown), min/max/step (slider), only ("web" or
 * "esp32" when a key applies to one target). Both settings UIs are built from this:
 * clockling.html directly, the ESP32 page via targets/esp32/tools/gen_assets.py.
 */

var TUNING_META = {
    /* Map of key -> { class: "Visible"|"Advanced", default: <value>, meaning: <string> } */
    tuning: {
        /* Map & resolution */
        mapW: { class: "Advanced", default: 216, meaning: "Battlefield width (px)" },
        mapH: { class: "Advanced", default: 432, meaning: "Battlefield height (px)" },

        /* Max units */
        maxLings: { class: "Visible", default: 30, meaning: "Max zerglings on screen" },
        maxBanes: { class: "Visible", default: 4, meaning: "Max banelings on screen" },
        maxMarines: { class: "Visible", default: 8, meaning: "Max marines on screen" },

        /* Movement */
        commandInterval: { class: "Visible", default: 1, meaning: "Real seconds between movement orders for every unit (smoother, less jerky); emergencies like a bane on a marine or lings in biting range still react at once. 0 = off", only: "web", min: 0, max: 3, step: 0.1 },
        zergSpeed: { class: "Visible", default: 1.2, meaning: "Zerg base speed multiplier" },
        terranSpeed: { class: "Visible", default: 1.35, meaning: "Terran base speed multiplier" },

        /* Zerg (zerglings, banelings, eggs) */
        respawnInterval: { class: "Visible", default: 17, meaning: "Seconds between ling-egg refill batches" },
        blueShellWait: { class: "Visible", default: 22, meaning: "Blue shell: REAL seconds of downtime after a wipe before the massive comeback (+-33%: about 15-30 s at the default)", only: "web", min: 10, max: 300, step: 5 },
        blueShellTrickles: { class: "Visible", default: 4, meaning: "Blue shell: up to this many small trickles (2-4 units each, at random moments) of the beaten side during its wait", only: "web", min: 0, max: 10, step: 1 },
        ddayMin: { class: "Visible", default: 3, meaning: "Blue shell D-day: the terran comeback after a wipe is at least this many times a normal wave (from both sides)", only: "web", min: 1, max: 10, step: 0.5 },
        ddayMax: { class: "Visible", default: 5, meaning: "Blue shell D-day: and at most this many times a normal wave", only: "web", min: 1, max: 20, step: 0.5 },
        blueShellPulse: { class: "Visible", default: 45, meaning: "Blue shell: game seconds between marine reinforcement pulses while marines are alive (each pulse refills their losses at once)", only: "web", min: 5, max: 90, step: 5 },
        blueShellBoost: { class: "Visible", default: 1, meaning: "Blue shell: a comeback can overfill the cap by this much (1 = up to double)", only: "web", min: 0, max: 3, step: 0.1 },
        blueShellDom: { class: "Visible", default: 2, meaning: "Blue shell: how strongly the losing side's waves stretch out and grow while the other side dominates", only: "web", min: 0, max: 6, step: 0.25 },
        startArmy: { class: "Visible", default: 0.7, meaning: "Both sides open the battle with this share of their caps (lings at a hive on one side, a full marine wave from the far edge), so the action starts at once", only: "web", min: 0, max: 1, step: 0.05 },
        growthRate: { class: "Visible", default: 0.5, meaning: "Growth mode: caps grow by this share of their base per minute", only: "web", min: 0.05, max: 2, step: 0.05 },
        growthEvery: { class: "Visible", default: 90, meaning: "Growth mode: real seconds between growth spurts (caps step up by growthRate x this / 60 each time)", only: "web", min: 10, max: 600, step: 10 },
        growthMax: { class: "Visible", default: 1.6, meaning: "Growth mode: caps stop growing at this multiple of their base", only: "web", min: 1, max: 20, step: 0.5 },
        zergWaveLo: { class: "Visible", default: 25, meaning: "Min seconds after the zerg are wiped out (no lings, banes or eggs) before eggs come back", only: "web" },
        zergWaveHi: { class: "Visible", default: 35, meaning: "Max seconds after the zerg are wiped out before eggs come back", only: "web" },
        respawnBatch: { class: "Visible", default: 10, meaning: "Eggs spawned per refill batch" },
        eggTimeMin: { class: "Visible", default: 40, meaning: "Min seconds until an egg hatches" },
        eggTimeMax: { class: "Visible", default: 60, meaning: "Max seconds until an egg hatches" },
        eggHatchMult: { class: "Advanced", default: 1.5, meaning: "Egg hatch acceleration multiplier" },
        eggHp: { class: "Visible", default: 100, meaning: "Egg hit points (eggs act as a tanky shield)", only: "web" },
        eggDamageMult: { class: "Visible", default: 0.1, meaning: "Fraction of normal damage an egg takes per hit (0.1 = 10%: about 40 shots)", only: "web", min: 0.0001, max: 1, step: 0.0005 },
        eggOverlap: { class: "Visible", default: 0, meaning: "How much a new egg may overlap another (0 = never touch, 1 = may stack)", only: "web", min: 0, max: 1, step: 0.05 },
        zergHomeQuadrant: { class: "Visible", default: false, meaning: "Eggs keep spawning around one home quadrant until the zerg are wiped out; the comeback brood picks a fresh home (farthest from the marines)", only: "web" },
        eggSpacing: { class: "Visible", default: 1.5, meaning: "New eggs are laid at least this many egg widths apart (before eggOverlap)", only: "web", min: 1, max: 6, step: 0.25 },
        eggMarineClearance: { class: "Visible", default: 0.8, meaning: "Eggs are laid at least this far from any marine (fraction of the board's short side), on the far side from the marines", only: "web", min: 0, max: 1, step: 0.05 },
        morphAge: { class: "Visible", default: 4, meaning: "Lings must live this long before morphing" },
        morphCooldown: { class: "Visible", default: 2, meaning: "Seconds between successful morphs" },
        morphChancePerSec: { class: "Visible", default: 1, meaning: "Chance per second to start morphing" },
        lingHp: { class: "Visible", default: 125, meaning: "Zergling hit points" },
        baneHp: { class: "Visible", default: 200, meaning: "Baneling hit points" },
        lingBiteDamage: { class: "Visible", default: 10, meaning: "Damage per zergling bite" },
        lingBiteInterval: { class: "Visible", default: 0.2, meaning: "Seconds between bites" },
        baneSplashDamage: { class: "Visible", default: 90, meaning: "Baneling blast damage" },
        baneSplashR: { class: "Visible", default: 61, meaning: "Baneling blast radius (px)" },
        zergGroupMode: { class: "Visible", default: true, meaning: "Control groups: the swarm moves as up to zergCgMax groups, banes travelling inside the ling groups; units in melee still fight alone. Off = every zerg moves alone", only: "web" },
        zergCgMax: { class: "Visible", default: 6, meaning: "zergGroupMode: most control groups the swarm splits into", only: "web", min: 1, max: 10, step: 1 },
        zergCgSize: { class: "Visible", default: 10, meaning: "zergGroupMode: lings per control group", only: "web", min: 2, max: 60, step: 1 },
        ovJoinRadius: { class: "Visible", default: 2.5, meaning: "Overmind (zergSkill 30%+): only zerg within this of the swarm's front (x marine range) count toward an attack; stragglers rally to the front", only: "web", min: 0.5, max: 10, step: 0.25 },
        ovSurround: { class: "Visible", default: 40, meaning: "Overmind (zergSkill 50%+): degrees each attacking ling arcs off the straight line so the swarm wraps around the marines", only: "web", min: 0, max: 80, step: 5 },
        ovBaneHold: { class: "Visible", default: true, meaning: "Overmind (zergSkill 50%+): banes ride in the pack until lings are biting a clump of marines", only: "web" },
        ovBaneClump: { class: "Visible", default: 2, meaning: "Overmind: marines that must stand inside a bane's splash before it rolls in", only: "web", min: 1, max: 8, step: 1 },
        ovBaneMaxHold: { class: "Visible", default: 6, meaning: "Overmind: longest a bane waits in the pack (s)", only: "web", min: 0, max: 30, step: 1 },
        ovFrontMorph: { class: "Visible", default: 0.3, meaning: "Overmind: how strongly morphs pick lings at the front line / near the terran spawn (x zergSkill; 0 = oldest lings)", only: "web", min: 0, max: 1, step: 0.05 },
        ovAllIn: { class: "Visible", default: true, meaning: "Overmind (zergSkill 50%+): save it all up - no new attack until the swarm is at ovAllInFrac of its cap with banes in, in a gap between marine reinforcements; then everything goes at once (a wall fight is the only exception)", only: "web" },
        ovMaxWait: { class: "Visible", default: 25, meaning: "Overmind: if the zerg haven't attacked for this many real seconds, they stop saving up and go with what they have (0 = wait as long as it takes)", only: "web", min: 0, max: 180, step: 5 },
        ovAllInFrac: { class: "Visible", default: 0.9, meaning: "ovAllIn: share of the full zerg cap (lings + banes) to build before the big push", only: "web", min: 0.3, max: 1, step: 0.05 },
        ovReinforceGap: { class: "Visible", default: 12, meaning: "ovAllIn: only push in a gap - at least half the current marine reinforcement cycle (capped at this many game-seconds) still to go", only: "web", min: 0, max: 60, step: 1 },
        ovWallPress: { class: "Visible", default: true, meaning: "Overmind: the big push comes in from the open side of the map so the marines get pressed back against their wall", only: "web" },
        ovMuster: { class: "Visible", default: 6, meaning: "Overmind (zergSkill 30%+): seconds a newborn ling gathers with its friends before it joins attacks; after that it only reinforces a fight as a pack of 5+", only: "web", min: 0, max: 30, step: 1 },
        ovBaneRatio: { class: "Visible", default: 0.5, meaning: "Overmind (zergSkill 50%+): banes needed per ling before any attack (0.25 = the 1:4 golden ratio; capped by the bane cap)", only: "web", min: 0, max: 1, step: 0.05 },
        ovBaneShare: { class: "Visible", default: 0.7, meaning: "Overmind (zergSkill 50%+): a swarm won't start an attack until this share of the bane cap has hatched (0 = don't wait); morphs speed up while it waits", only: "web", min: 0, max: 1, step: 0.05 },
        ovBaneVanguard: { class: "Visible", default: 0.5, meaning: "Overmind: share of a committing swarm's banes that lead at ling pace to break the marine line (the rest hold in the pack for a clump)", only: "web", min: 0, max: 1, step: 0.05 },
        ovEncircle: { class: "Visible", default: false, meaning: "(experimental) Overmind (zergSkill 50%+): attacking lings that can't reach a marine run round the outside to the far side and close the ring - encircled marines can't kite", only: "web" },
        ovGuardBanes: { class: "Visible", default: true, meaning: "Overmind (zergSkill 40%+): up to 3 idle lings step between a hunted baneling and its hunter to draw fire, peeling off below half HP", only: "web" },
        zergNoHope: { class: "Visible", default: 0.15, meaning: "A committed swarm fights to the death unless the whole swarm drops below this share of the strength the fight needs (attackOdds x marines)", only: "web", min: 0, max: 1, step: 0.05 },
        zergSmarts: { class: "Visible", default: true, meaning: "A swarm ready to attack stalks first, circling the marines just out of range, and only commits when cornered, overwhelming them or out of patience (off = it charges straight in)", only: "web" },
        zergPatience: { class: "Visible", default: 3, meaning: "zergSmarts: seconds a stalking swarm circles before it attacks anyway", only: "web", min: 0, max: 180, step: 5 },
        zergAllInOdds: { class: "Visible", default: 1, meaning: "zergSmarts: a stalking swarm attacks at once when it has this many times attackOdds (0 = never)", only: "web", min: 0, max: 10, step: 0.5 },
        zergStandoff: { class: "Advanced", default: 1.3, meaning: "zergSmarts: stalking ring radius (x marine range)", only: "web", min: 1, max: 3, step: 0.05 },
        zergCornerDist: { class: "Advanced", default: 0.18, meaning: "zergSmarts: a swarm this close to walls (x board short side) with marines near counts as cornered and attacks", only: "web", min: 0, max: 0.5, step: 0.01 },
        attackGroupSize: { class: "Visible", default: 10, meaning: "Minimum swarm strength (ling 1, bane 2) to attack; capped at maxLings" },
        berserkBanes: { class: "Visible", default: 2, meaning: "Banelings alive needed to trigger bane berserk" },
        berserkUntilDeath: { class: "Visible", default: false, meaning: "On: berserk never retreats; off: cancels when outnumbered" },
        attackOdds: { class: "Visible", default: 1.2, meaning: "Swarm strength (ling 1, bane 2) needed per marine in the target group" },
        allyRadius: { class: "Visible", default: 45, meaning: "Lings/banes this close to each other count as one swarm" },
        marineScanRadius: { class: "Visible", default: 140, meaning: "Lings flee marines inside this radius (never less than 1.25x marine range)" },
        marineGroupRadius: { class: "Visible", default: 60, meaning: "Radius around a marine used to count its group" },
        berserkCatchRadius: { class: "Visible", default: 80, meaning: "Lings catch berserk from a berserk bane within this radius" },
        berserkSpeedMult: { class: "Visible", default: 1.5, meaning: "Speed multiplier while berserk" },
        lingAttackBoostMult: { class: "Visible", default: 1.5, meaning: "Speed burst for every ling that joins an attack (berserk lings get the larger of this and berserk speed)", only: "web", min: 1, max: 3, step: 0.1 },
        lingAttackBoostTime: { class: "Visible", default: 3, meaning: "Seconds the attack speed burst lasts", only: "web", min: 0, max: 10, step: 0.5 },
        lingAttackBoostCooldown: { class: "Visible", default: 5, meaning: "Seconds after a burst ends before a ling can burst again", only: "web", min: 0, max: 30, step: 0.5 },
        lingFleeSpeedMult: { class: "Visible", default: 1.6, meaning: "Speed multiplier for lings escaping marines" },

        /* Terran (marines) */
        marineSpawnRateMult: { class: "Visible", default: 1.5, meaning: "Marine spawn rate multiplier" },
        marineWaveLo: { class: "Visible", default: 8, meaning: "Min seconds after all marines die" },
        marineWaveHi: { class: "Visible", default: 10, meaning: "Max seconds after all marines die" },
        marineRespawnLo: { class: "Visible", default: 4, meaning: "Min seconds between respawns" },
        marineRespawnHi: { class: "Visible", default: 6, meaning: "Max seconds between respawns" },
        marineSpawnGap: { class: "Visible", default: 0.5, meaning: "Seconds between marines in wave" },
        marineSpawnInset: { class: "Advanced", default: 6, meaning: "Px off-screen spawn distance" },
        marineWaveSizeLo: { class: "Visible", default: 6, meaning: "Min marines per wave" },
        marineWaveSizeHi: { class: "Visible", default: 6, meaning: "Max marines per wave" },
        marineRespawnSizeLo: { class: "Visible", default: 3, meaning: "Min marines per respawn" },
        marineRespawnSizeHi: { class: "Visible", default: 4, meaning: "Max marines per respawn" },
        marineHp: { class: "Visible", default: 120, meaning: "Marine hit points" },
        marineShootDamage: { class: "Visible", default: 25, meaning: "Damage per marine shot" },
        marineShootInterval: { class: "Visible", default: 0.36, meaning: "Seconds between shots" },
        marineRangeMult: { class: "Visible", default: 3, meaning: "Weapon range multiplier" },
        marineFleeHpPct: { class: "Advanced", default: 0.9, meaning: "Marines kite away below this HP fraction" },
        marineKiteFrac: { class: "Visible", default: 0.6, meaning: "Marines back off from zerg closer than this fraction of their range" },
        marineSightMult: { class: "Visible", default: 2, meaning: "Marines patrol when no zerg is within this x weapon range" },
        dropPointsMax: { class: "Visible", default: 4, meaning: "Marine waves arrive all at once from 1 to this many drop points close together (dropships / barracks off-screen); the blue shell comeback floods in from 8-10 points round the map", only: "web", min: 1, max: 6, step: 1 },
        marineSpawnAnchor: { class: "Advanced", default: true, meaning: "Semi-static marine spawn: each wave's entry point shifts at most marineSpawnDrift of the board from the last one", only: "web" },
        marineSideSwap: { class: "Advanced", default: 150, meaning: "marineSpawnAnchor: marines spawn from one home side and may switch sides at most every this many real seconds (D-day comebacks excepted)", only: "web", min: 0, max: 900, step: 30 },
        marineSpawnDrift: { class: "Advanced", default: 0.25, meaning: "marineSpawnAnchor: how far a wave's entry point may move along the border (x half the perimeter)", only: "web", min: 0, max: 1, step: 0.05 },
        marineSpawnMode: { class: "Visible", default: 0, meaning: "Where marine waves enter: 0 far from the zerg, 1 behind the marines already fighting, 2 strategist (reinforce while they hold, land far away when they're overrun)", only: "web", min: 0, max: 2, step: 1 },
        marineEntrySpeed: { class: "Visible", default: 1.5, meaning: "Speed multiplier while new marines march in from off-screen" },
        marineEntryDepth: { class: "Visible", default: 0.09, meaning: "March-in boost stops this far inside the edge (x shorter side)" },
        marineGroupWeight: { class: "Advanced", default: 0.5, meaning: "Pull toward other marines" },
        marineAwayWeight: { class: "Advanced", default: 1, meaning: "Push away from zerg" },
        marineTurnRate: { class: "Advanced", default: 0.25, meaning: "Marine steering: share of the turn closed every 1/8 s" },
        marineTactics: { class: "Visible", default: true, meaning: "New marine AI: kite, regroup, or advance" },
        marineHealPct: { class: "Advanced", default: 0.10, meaning: "HP all units heal per tick" },
        marineHealInterval: { class: "Advanced", default: 0.5, meaning: "Seconds between heal ticks" },
        stimDuration: { class: "Visible", default: 3, meaning: "Seconds a stimpack lasts", only: "web", min: 0.5, max: 10, step: 0.5 },
        stimCooldown: { class: "Visible", default: 10, meaning: "Seconds before a marine can stim again", only: "web", min: 0, max: 60, step: 1 },
        stimSpeedMult: { class: "Visible", default: 2, meaning: "Speed multiplier while stimmed", only: "web", min: 1, max: 4, step: 0.1 },
        stimHpCost: { class: "Visible", default: 0.5, meaning: "Share of MAX HP each stimpack costs (it can kill: green marines may stim themselves to death)", only: "web", min: 0, max: 0.9, step: 0.05 },
        stimRegenMult: { class: "Visible", default: 0, meaning: "HP regen multiplier after a stim (for stimRegenTime)", only: "web", min: 0, max: 1, step: 0.05 },
        stimFireMult: { class: "Visible", default: 1.5, meaning: "Fire-rate multiplier while stimmed (on top of the speed boost)", only: "web", min: 1, max: 3, step: 0.1 },
        stimRegenTime: { class: "Visible", default: 20, meaning: "Seconds of slowed regen from the moment a marine stims", only: "web", min: 0, max: 60, step: 1 },
        stimGroupMax: { class: "Visible", default: 3, meaning: "Only marine groups this small (or smaller) stim to escape", only: "web", min: 1, max: 20, step: 1 },
        stimRegroupDist: { class: "Visible", default: 0.15, meaning: "Lone marines farther than this from the main mob (x board short side) stim back to it", only: "web", min: 0.05, max: 1, step: 0.05 },
        marineKiteSpeed: { class: "Visible", default: 0.5, meaning: "Speed multiplier while kiting / running back to the mob (on top of skill footwork and stim): keeps escapes to short hops", only: "web", min: 0.25, max: 2, step: 0.05 },
        marineUpright: { class: "Visible", default: true, meaning: "Marines stand upright (feet down) when not firing, facing and leaning with their squad's walk; off = they always face the closest zerg, leaning at most marineMaxTilt", only: "web" },
        marineWalkTilt: { class: "Visible", default: 25, meaning: "marineUpright: max degrees a marine leans from upright while walking (it turns fully to its target when firing)", only: "web", min: 0, max: 60, step: 1 },
        marineGroupMode: { class: "Visible", default: true, meaning: "Control groups: marines move as up to marineCgMax groups (by proximity), each on one shared move like a human with hotkeys; off = every marine micros alone", only: "web" },
        marineCgMax: { class: "Visible", default: 5, meaning: "marineGroupMode: most control groups the marines split into", only: "web", min: 1, max: 10, step: 1 },
        marineCgSize: { class: "Visible", default: 6, meaning: "marineGroupMode: marines per control group (more marines = more groups, up to marineCgMax)", only: "web", min: 2, max: 30, step: 1 },
        marineHitSquads: { class: "Visible", default: true, meaning: "Commander hit squads (control groups, 50%+ skill): once the zerg are weakened, the healthiest marines break off, stim and hunt - eggs first, then the nearest zerg", only: "web" },
        hitSquadSize: { class: "Visible", default: 4, meaning: "Marines in a hit squad", only: "web", min: 2, max: 10, step: 1 },
        hitSquadTrigger: { class: "Visible", default: 0.45, meaning: "Send a hit squad once the zerg are below this share of their cap (or terran is clearly on top)", only: "web", min: 0.1, max: 1, step: 0.05 },
        marineMicro: { class: "Visible", default: true, meaning: "Per-marine micro (50%+ skill), like SC2 bots: stutter-step back while the gun cools down, fire when ready, and split away from banelings", only: "web" },
        marineBaneHunt: { class: "Visible", default: true, meaning: "The 1-2 closest healthy marines (60%+ skill) stim forward and shoot a bane that isn\'t charging - in the open or stuck among them - keeping out of its splash", only: "web" },
        marineStimAttack: { class: "Visible", default: true, meaning: "A healthy marine group (3+, 60%+ skill) in a fight it can win stims together and pushes in hard", only: "web" },
        marineSquads: { class: "Visible", default: true, meaning: "Split kiting: a big marine mob splits into control groups that kite independently, taking turns to backstep and peeling apart to pull the swarm apart (off = the whole mob kites as one)", only: "web" },
        marineCtrlGroups: { class: "Visible", default: 4, meaning: "marineSquads: most control groups one mob splits into (2 below 75% skill, none below 50%)", only: "web", min: 1, max: 8, step: 1 },
        marineCtrlGroupSize: { class: "Visible", default: 6, meaning: "marineSquads: marines per control group (a mob of 12 makes 2 groups, 40 makes marineCtrlGroups)", only: "web", min: 2, max: 20, step: 1 },
        marineFlank: { class: "Visible", default: true, meaning: "Marines advance on a flank instead of straight at the zerg", only: "web" },
        marineStimPush: { class: "Visible", default: true, meaning: "Stimmed elite marines (75%+ skill) push in while firing and kite back later", only: "web" },
        marineEliteKite: { class: "Visible", default: true, meaning: "Elite marines (75%+ skill) stutter-step whenever lings close in", only: "web" },
        marineFlankAngle: { class: "Visible", default: 45, meaning: "Degrees off the direct line marines advance at, so they come in on a flank (scaled by skill; straight in when they overwhelm 3:1)", only: "web", min: 0, max: 80, step: 5 },
        marineMaxTilt: { class: "Visible", default: 45, meaning: "Max degrees a marine sprite leans from level when aiming up or down (feet stay down)", only: "web", min: 0, max: 90, step: 5 },
        marineSkillTopSpeed: { class: "Advanced", default: 3, meaning: "Movement multiplier at max marine skill (1x at half skill)", only: "web", min: 1, max: 4, step: 0.1 },

        /* Visuals & timing */
        lingW: { class: "Advanced", default: 30, meaning: "Zergling sprite width (px)" },
        baneW: { class: "Advanced", default: 39, meaning: "Baneling sprite width (px)" },
        marineW: { class: "Advanced", default: 42, meaning: "Marine sprite width (px)" },
        eggW: { class: "Advanced", default: 21, meaning: "Egg sprite width (px)" },
        lingBump: { class: "Advanced", default: 10, meaning: "Zergling collision radius" },
        baneBump: { class: "Advanced", default: 12, meaning: "Baneling collision radius" },
        marineBump: { class: "Advanced", default: 12, meaning: "Marine collision radius" },
        splatLife: { class: "Advanced", default: 1.21, meaning: "Death-splat lifetime (s)" },
        splatBase: { class: "Advanced", default: 7, meaning: "Splat start radius (px)" },
        splatFadeStart: { class: "Advanced", default: 0.6, meaning: "Splat fade start fraction" },
        corpseLife: { class: "Advanced", default: 2.2, meaning: "Dead sprite lingers (s)" },
        goreSplatLife: { class: "Advanced", default: 16.2, meaning: "Gore mode: death splat lingers (s)" },
        goreCorpseLife: { class: "Advanced", default: 19.2, meaning: "Gore mode: corpse lingers (s)" },
        baneSplatLifeMult: { class: "Advanced", default: 0.3, meaning: "Green (baneling) splat lifetime x red splat lifetime" },
        marineSplatScale: { class: "Advanced", default: 1.4, meaning: "Marine splat scale" },
        baneSplatScale: { class: "Advanced", default: 2.5, meaning: "Baneling splat scale" },
        retargetInterval: { class: "Advanced", default: 0.5, meaning: "Ling/bane retarget interval (s)" },
        aimInterval: { class: "Advanced", default: 0.3, meaning: "Marine re-aim interval (s)" }
    },

    /* Map of SETTINGS key -> { class, meaning } (defaults live in settings.js) */
    settings: {
        showClock: { class: "Visible", meaning: "Show the clock" },
        hour24: { class: "Visible", meaning: "24-hour clock (off = 12-hour)" },
        showSeconds: { class: "Visible", meaning: "Show seconds" },
        clockPosition: { class: "Visible", meaning: "Where the clock sits",
                         options: ["Top", "Middle", "Bottom", "Top left", "Top right", "Bottom left", "Bottom right"] },
        clockBehind: { class: "Visible", meaning: "Draw the clock behind the units" },
        clockScale: { class: "Visible", meaning: "Clock size", only: "web", min: 0.5, max: 2, step: 0.05 },
        timeZone: { class: "Visible", meaning: "Time zone (auto = this device)", only: "web" },
        gameSpeed: { class: "Visible", meaning: "Speed multiplier", min: 0.25, max: 5, step: 0.25 },
        unitScale: { class: "Visible", meaning: "Unit multiplier (population, waves, spawn rate)", min: 0.5, max: 5, step: 0.5 },
        unitCount: { class: "Advanced", meaning: "Starting zerglings" },
        marineSkill: { class: "Visible", meaning: "Marine smarts: 0 = stand and die, 1 = one marine can dance around a swarm", only: "web", min: 0, max: 1, step: 0.05 },
        zergBrain: { class: "Visible", meaning: "Overmind brain: Default = the tuning panel, Trained = the self-play champion (tools/sim/train.js)", only: "web", options: ["Default", "Trained"] },
        terranBrain: { class: "Visible", meaning: "Commander brain: Default = the tuning panel, Trained = the self-play champion (tools/sim/train.js)", only: "web", options: ["Default", "Trained"] },
        unlockMultipliers: { class: "Visible", meaning: "Unlock speed & units: type any Speed / Units multiplier (up to 50x) instead of using the sliders", only: "web" },
        blueShell: { class: "Visible", meaning: "Blue shell: a wiped side sits out ~a minute then comes back huge, the losing side's reinforcements come less often but bigger, and with the terrans gone the zerg lay dormant eggs all over the map", only: "web" },
        growthMode: { class: "Visible", meaning: "Growth mode: both sides keep getting reinforcements beyond the caps until one wipes the other off the board, then caps reset", only: "web" },
        zergSkill: { class: "Visible", meaning: "Overmind smarts: 0 = every swarm piles in, 1 = backup gathers, lings surround, banes wait for a clump", only: "web", min: 0, max: 1, step: 0.05 },
        unitSpeed: { class: "Advanced", meaning: "Movement speed multiplier for every unit" },
        showHealthBars: { class: "Visible", meaning: "Show unit health bars" },
        showKills: { class: "Visible", meaning: "Marine kill marks (one per ling killed)", only: "web" },
        gore: { class: "Visible", meaning: "Gore mode: splats and corpses linger (splat 16.2 s, corpse 19.2 s)" },
        fieldSize: { class: "Visible", meaning: "Battlefield size (smaller = bigger units)", only: "web",
                     options: { "480": "Small", "640": "Medium", "960": "Large", "1280": "Huge" } },
        soundOn: { class: "Visible", meaning: "Play sound effects", only: "web" },
        soundVolume: { class: "Visible", meaning: "Sound volume", only: "web", min: 0, max: 100, step: 5 },
        soundRate: { class: "Visible", meaning: "How often chatter and voicelines play (0 = never)", only: "web", min: 0, max: 3, step: 0.25 },
        musicTrack: { class: "Visible", meaning: "Background music", only: "web",
                      options: ["Off", "Zerg", "Protoss", "Terran 1", "Terran 2", "Terran 3", "All (in order)"] },
        musicVolume: { class: "Visible", meaning: "Music volume", only: "web", min: 0, max: 100, step: 5 },
        landscape: { class: "Visible", meaning: "Horizontal screen (off = vertical)", only: "esp32" }
    },

    /* Groups for UI organization */
    groups: {
        "Zerg Rules": ["zergGroupMode", "zergCgMax", "zergCgSize", "ovJoinRadius", "ovSurround", "ovBaneHold", "ovBaneClump", "ovBaneMaxHold", "ovFrontMorph", "ovBaneRatio", "ovAllIn", "ovMaxWait", "ovAllInFrac", "ovReinforceGap", "ovWallPress", "ovMuster", "ovBaneShare", "ovBaneVanguard", "ovEncircle", "ovGuardBanes", "zergNoHope", "zergSmarts", "zergPatience", "zergAllInOdds", "zergStandoff", "zergCornerDist", "attackGroupSize", "lingFleeSpeedMult", "berserkBanes", "berserkUntilDeath", "attackOdds", "allyRadius", "marineScanRadius", "marineGroupRadius", "berserkCatchRadius"],
        "Zerg Units": ["maxLings", "maxBanes", "lingHp", "baneHp", "lingBiteDamage", "lingBiteInterval", "baneSplashDamage", "baneSplashR", "berserkSpeedMult", "lingAttackBoostMult", "lingAttackBoostTime", "lingAttackBoostCooldown"],
        "Zerg Lifecycle": ["blueShellWait", "blueShellTrickles", "ddayMin", "ddayMax", "blueShellPulse", "blueShellBoost", "blueShellDom", "startArmy", "growthRate", "growthEvery", "growthMax", "respawnInterval", "zergWaveLo", "zergWaveHi", "respawnBatch", "eggTimeMin", "eggTimeMax", "eggHatchMult", "eggHp", "eggDamageMult", "eggOverlap", "eggSpacing", "zergHomeQuadrant", "eggMarineClearance", "morphAge", "morphCooldown", "morphChancePerSec"],
        "Terran Units": ["maxMarines", "marineHp", "marineShootDamage", "marineShootInterval", "marineRangeMult"],
        "Terran Spawning": ["dropPointsMax", "marineSpawnAnchor", "marineSideSwap", "marineSpawnDrift", "marineSpawnMode", "marineEntrySpeed", "marineEntryDepth", "marineSpawnRateMult", "marineWaveLo", "marineWaveHi", "marineWaveSizeLo", "marineWaveSizeHi", "marineRespawnLo", "marineRespawnHi", "marineRespawnSizeLo", "marineRespawnSizeHi", "marineSpawnGap", "marineSpawnInset"],
        "Terran Behavior": ["marineTactics", "marineKiteFrac", "marineSightMult", "marineFleeHpPct", "marineGroupWeight", "marineAwayWeight", "marineTurnRate", "marineHealPct", "marineHealInterval", "stimDuration", "stimCooldown", "stimSpeedMult", "stimHpCost", "stimRegenMult", "stimFireMult", "stimRegenTime", "stimGroupMax", "stimRegroupDist", "marineKiteSpeed", "marineUpright", "marineWalkTilt", "marineGroupMode", "marineCgMax", "marineCgSize", "marineHitSquads", "hitSquadSize", "hitSquadTrigger", "marineMicro", "marineBaneHunt", "marineStimAttack", "marineSquads", "marineCtrlGroups", "marineCtrlGroupSize", "marineFlank", "marineStimPush", "marineEliteKite", "marineFlankAngle", "marineMaxTilt", "marineSkillTopSpeed"],
        "Movement": ["commandInterval", "zergSpeed", "terranSpeed"],
        "Visuals": ["lingW", "baneW", "marineW", "eggW", "lingBump", "baneBump", "marineBump", "splatLife", "splatBase", "splatFadeStart", "corpseLife", "goreSplatLife", "goreCorpseLife", "baneSplatLifeMult", "marineSplatScale", "baneSplatScale", "retargetInterval", "aimInterval"],
        "Map": ["mapW", "mapH"],
        "Clock": ["showClock", "hour24", "showSeconds", "clockPosition", "clockBehind", "clockScale", "timeZone"],
        "Battle": ["gameSpeed", "unitScale", "fieldSize", "showHealthBars", "showKills", "gore", "unitCount", "unitSpeed", "unlockMultipliers", "blueShell", "growthMode", "marineSkill", "zergSkill", "zergBrain", "terranBrain", "soundOn", "soundVolume", "soundRate", "musicTrack", "musicVolume"],
        "Display": ["landscape"]
    }
};
